CREATE TABLE venta (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sucursal_id BIGINT NOT NULL,
    usuario_id BIGINT NOT NULL,
    total NUMERIC(12,2) NOT NULL,
    lista_precio VARCHAR(255),
    estado VARCHAR(255) NOT NULL,
    fecha TIMESTAMP NOT NULL,
    CONSTRAINT fk_venta_sucursal FOREIGN KEY (sucursal_id) REFERENCES sucursal(id),
    CONSTRAINT fk_venta_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id),
    CONSTRAINT chk_venta_estado CHECK (estado IN ('CONFIRMADA', 'ANULADA'))
);