CREATE TABLE venta_detalle (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venta_id BIGINT NOT NULL,
    producto_id BIGINT NOT NULL,
    cantidad NUMERIC(12,2) NOT NULL,
    precio_unitario NUMERIC(12,2) NOT NULL,
    descuento NUMERIC(12,2) DEFAULT 0,
    CONSTRAINT fk_ventadetalle_venta FOREIGN KEY (venta_id) REFERENCES venta(id),
    CONSTRAINT fk_ventadetalle_producto FOREIGN KEY (producto_id) REFERENCES producto(id)
);