CREATE TABLE proveedor (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    nombre_contacto VARCHAR(255),
    telefono VARCHAR(255),
    email VARCHAR(255),
    tiempo_entrega_promedio_dias INTEGER
);