CREATE TABLE orden_compra (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proveedor_id BIGINT NOT NULL,
    sucursal_id BIGINT NOT NULL,
    usuario_id BIGINT NOT NULL,
    estado VARCHAR(255) NOT NULL,
    condiciones_pago VARCHAR(255),
    fecha TIMESTAMP NOT NULL,
    CONSTRAINT fk_ordencompra_proveedor FOREIGN KEY (proveedor_id) REFERENCES proveedor(id),
    CONSTRAINT fk_ordencompra_sucursal FOREIGN KEY (sucursal_id) REFERENCES sucursal(id),
    CONSTRAINT fk_ordencompra_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id),
    CONSTRAINT chk_ordencompra_estado CHECK (estado IN ('PENDIENTE', 'RECIBIDA', 'CANCELADA'))
);