CREATE TABLE orden_compra_detalle (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    orden_compra_id BIGINT NOT NULL,
    producto_id BIGINT NOT NULL,
    cantidad NUMERIC(12,2) NOT NULL,
    precio_unitario NUMERIC(12,2) NOT NULL,
    descuento NUMERIC(12,2) DEFAULT 0,
    CONSTRAINT fk_ocdetalle_orden FOREIGN KEY (orden_compra_id) REFERENCES orden_compra(id),
    CONSTRAINT fk_ocdetalle_producto FOREIGN KEY (producto_id) REFERENCES producto(id)
);