CREATE TABLE usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    rol VARCHAR(255) NOT NULL,
    sucursal_id BIGINT,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_usuario_email UNIQUE (email),
    CONSTRAINT fk_usuario_sucursal FOREIGN KEY (sucursal_id) REFERENCES sucursal(id),
    CONSTRAINT chk_usuario_rol CHECK (rol IN ('ADMIN_GENERAL', 'GERENTE_SUCURSAL', 'OPERADOR_INVENTARIO'))
);