CREATE TABLE movimiento_inventario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_id BIGINT NOT NULL,
    sucursal_id BIGINT NOT NULL,
    usuario_id BIGINT NOT NULL,
    tipo VARCHAR(255) NOT NULL,
    motivo VARCHAR(255) NOT NULL,
    cantidad NUMERIC(12,2) NOT NULL,
    costo_unitario NUMERIC(12,2),
    referencia_tipo VARCHAR(255),
    referencia_id BIGINT,
    fecha TIMESTAMP NOT NULL,
    CONSTRAINT fk_movimiento_producto FOREIGN KEY (producto_id) REFERENCES producto(id),
    CONSTRAINT fk_movimiento_sucursal FOREIGN KEY (sucursal_id) REFERENCES sucursal(id),
    CONSTRAINT fk_movimiento_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id),
    CONSTRAINT chk_movimiento_tipo CHECK (tipo IN ('INGRESO', 'RETIRO')),
    CONSTRAINT chk_movimiento_motivo CHECK (motivo IN ('COMPRA', 'DEVOLUCION', 'AJUSTE', 'VENTA', 'MERMA', 'TRANSFERENCIA'))
);