CREATE TABLE transferencia (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sucursal_origen_id BIGINT NOT NULL,
    sucursal_destino_id BIGINT NOT NULL,
    usuario_solicita_id BIGINT NOT NULL,
    estado VARCHAR(255) NOT NULL,
    urgencia VARCHAR(255) NOT NULL,
    fecha_solicitud TIMESTAMP NOT NULL,
    CONSTRAINT fk_transferencia_origen FOREIGN KEY (sucursal_origen_id) REFERENCES sucursal(id),
    CONSTRAINT fk_transferencia_destino FOREIGN KEY (sucursal_destino_id) REFERENCES sucursal(id),
    CONSTRAINT fk_transferencia_usuario FOREIGN KEY (usuario_solicita_id) REFERENCES usuario(id),
    CONSTRAINT chk_transferencia_estado CHECK (estado IN ('SOLICITADA','EN_PREPARACION','EN_TRANSITO','RECIBIDA_COMPLETA','RECIBIDA_PARCIAL')),
    CONSTRAINT chk_transferencia_urgencia CHECK (urgencia IN ('BAJA','MEDIA','ALTA')),
    CONSTRAINT chk_transferencia_sucursales_distintas CHECK (sucursal_origen_id <> sucursal_destino_id)
);