CREATE TABLE transferencia_detalle (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transferencia_id BIGINT NOT NULL,
    producto_id BIGINT NOT NULL,
    cantidad_solicitada NUMERIC(12,2) NOT NULL,
    cantidad_enviada NUMERIC(12,2),
    cantidad_recibida NUMERIC(12,2),
    CONSTRAINT fk_detalle_transferencia FOREIGN KEY (transferencia_id) REFERENCES transferencia(id),
    CONSTRAINT fk_detalle_producto FOREIGN KEY (producto_id) REFERENCES producto(id)
);