CREATE TABLE envio (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transferencia_id BIGINT NOT NULL,
    transportista VARCHAR(255),
    fecha_envio DATE,
    fecha_estimada_llegada DATE,
    fecha_real_llegada DATE,
    estado VARCHAR(255) NOT NULL,
    costo_envio NUMERIC(12,2),
    prioridad VARCHAR(255),
    CONSTRAINT fk_envio_transferencia FOREIGN KEY (transferencia_id) REFERENCES transferencia(id),
    CONSTRAINT chk_envio_estado CHECK (estado IN ('EN_PREPARACION','EN_TRANSITO','ENTREGADO','CON_FALTANTES'))
);